# Generated by Django 2.0.4 on 2018-04-26 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=6000)),
                ('date_commentaire', models.DateField()),
                ('have_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='DemandesAmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.IntegerField(choices=[(0, 'En Cours'), (1, 'Acceptée'), (2, 'Refusée'), (3, 'Bloquée')])),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('activite', models.CharField(max_length=255)),
                ('secteurActivite', models.CharField(choices=[('Publique', 'Publique'), ('Prive', 'Privé')], max_length=255)),
                ('capitale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pays', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('codePostal', models.IntegerField()),
                ('telephone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('siteInternet', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateField()),
                ('statut_groupe', models.CharField(choices=[('Publique', 'Publique'), ('Prive', 'Privé')], max_length=255)),
                ('have_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('message', models.CharField(max_length=1000)),
                ('statut', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('website', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('adresse', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Entreprise')),
                ('photo_couverture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_cover', to='SocialMedia.Image')),
                ('photo_profil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_photo', to='SocialMedia.Image')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responseconversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=6000)),
                ('message_date', models.DateTimeField()),
                ('is_image', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Conversation')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Image')),
                ('user_responsed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_statut', models.DateTimeField()),
                ('contenu_statut', models.CharField(max_length=6000)),
                ('is_group_statut', models.BooleanField(default=False)),
                ('is_profil_statut', models.BooleanField(default=False)),
                ('liked_by', models.ManyToManyField(related_name='like', to='SocialMedia.Profil')),
                ('mur_groupe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Groupe')),
                ('mur_profil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_mur', to='SocialMedia.Profil')),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pub', to='SocialMedia.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Suivie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suive', to='SocialMedia.Profil')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suiveur', to='SocialMedia.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEntreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('publique', 'publique'), ('prive', 'prive')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='profil_to_notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='adherents',
            field=models.ManyToManyField(related_name='adherent', to='SocialMedia.Profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='admins',
            field=models.ManyToManyField(related_name='admin', to='SocialMedia.Profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='createur', to='SocialMedia.Profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='mederators',
            field=models.ManyToManyField(related_name='moderateur', to='SocialMedia.Profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='photo_couverture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_cover', to='SocialMedia.Image'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='photo_profil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_photo', to='SocialMedia.Image'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='typeEntreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.TypeEntreprise'),
        ),
        migrations.AddField(
            model_name='demandesami',
            name='emetteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='SocialMedia.Profil'),
        ),
        migrations.AddField(
            model_name='demandesami',
            name='recepteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='SocialMedia.Profil'),
        ),
        migrations.AddField(
            model_name='demandegroupe',
            name='emetteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Profil'),
        ),
        migrations.AddField(
            model_name='demandegroupe',
            name='groupe_recepteur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Groupe'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Image'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='liked_by',
            field=models.ManyToManyField(to='SocialMedia.Profil'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='statut',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Statut'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to='SocialMedia.Profil'),
        ),
    ]
