# Generated by Django 2.0.5 on 2018-05-09 16:44

import SocialMedia.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionBenevole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organisme', models.CharField(max_length=300)),
                ('nom_poste', models.CharField(max_length=300)),
                ('cause', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('date_creation', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=6000)),
                ('date_commentaire', models.DateField()),
                ('have_image', models.BooleanField(default=False)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Image')),
                ('liked_by', models.ManyToManyField(to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.IntegerField(choices=[(0, 'En Cours'), (1, 'Acceptée'), (2, 'Refusée'), (3, 'Bloquée')])),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main_app.Profil')),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.BooleanField()),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='SocialMedia/Image/')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=300)),
                ('nom_poste', models.CharField(max_length=300)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actuel', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_formation', models.CharField(max_length=300)),
                ('nom_ecole', models.CharField(max_length=300)),
                ('domaine', models.CharField(blank=True, max_length=300, null=True)),
                ('resultat_obtenu', models.CharField(blank=True, max_length=300, null=True)),
                ('activite_et_associations', models.TextField(blank=True, null=True)),
                ('annee_debut', models.DateField()),
                ('annee_fin', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Ecole')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateField()),
                ('statut_groupe', models.CharField(choices=[('publique', 'publique'), ('prive', 'privé')], max_length=255)),
                ('have_image', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('adherents', models.ManyToManyField(related_name='adherent', to='main_app.Profil')),
                ('admins', models.ManyToManyField(related_name='admin', to='main_app.Profil')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='createur', to='main_app.Profil')),
                ('mederators', models.ManyToManyField(related_name='moderateur', to='main_app.Profil')),
                ('photo_couverture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_cover', to='main_app.Image')),
                ('photo_profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_photo', to='main_app.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('expert', 'Expert')], max_length=300)),
                ('profils', models.ManyToManyField(related_name='profils', to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('message', models.CharField(max_length=1000)),
                ('statut', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(default=False)),
                ('profil_to_notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pays', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=300)),
                ('diplome_requis', models.CharField(max_length=300)),
                ('type_contrat', models.CharField(max_length=300)),
                ('description_poste', models.TextField()),
                ('profil_recherche', models.TextField()),
                ('presentation_entreprise', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('type_emploi', models.CharField(choices=[('plein', 'Plein temps'), ('partiel', 'Temps partiel')], max_length=300)),
                ('nom_poste', models.CharField(max_length=300)),
                ('en_cours', models.BooleanField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='SocialMedia/Image/')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_poste', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ReseauSocialFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=SocialMedia.models.generate_path)),
                ('date_telechargement', models.DateTimeField()),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Album')),
                ('comment', models.ManyToManyField(to='SocialMedia.Commentaire')),
                ('likes', models.ManyToManyField(to='SocialMedia.Like')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Responseconversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=6000)),
                ('message_date', models.DateTimeField()),
                ('is_image', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Conversation')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Image')),
                ('user_responsed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_statut', models.DateTimeField()),
                ('contenu_statut', models.CharField(max_length=6000)),
                ('is_group_statut', models.BooleanField(default=False)),
                ('is_profil_statut', models.BooleanField(default=False)),
                ('liked_by', models.ManyToManyField(related_name='statut_liked_by', to='main_app.Profil')),
                ('mur_groupe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Groupe')),
                ('mur_profil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut_mur_profil', to='main_app.Profil')),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pub', to='main_app.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Suivie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suive', to='main_app.Profil')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suiveur', to='main_app.Profil')),
            ],
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poste_recherche', to='SocialMedia.Poste'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='profil_postulants',
            field=models.ManyToManyField(blank=True, related_name='profil_postulants', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='profil_publicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_publicateur', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='experience',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Poste'),
        ),
        migrations.AddField(
            model_name='experience',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='demandegroupe',
            name='groupe_recepteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Groupe'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='statut',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Statut'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='actionbenevole',
            name='organisme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Organisme'),
        ),
        migrations.AddField(
            model_name='actionbenevole',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Poste'),
        ),
        migrations.AddField(
            model_name='actionbenevole',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AlterUniqueTogether(
            name='suivie',
            unique_together={('follower', 'followed_profil')},
        ),
    ]
