# Generated by Django 2.0.5 on 2018-05-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupe',
            old_name='mederators',
            new_name='moderators',
        ),
    ]
