# Generated by Django 2.0.3 on 2018-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemandesAmi',
            new_name='DemandeAmi',
        ),
        migrations.RemoveField(
            model_name='myprofil',
            name='adresse',
        ),
        migrations.AddField(
            model_name='myprofil',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myprofil',
            name='fonction',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myprofil',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myprofil',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myprofil',
            name='pays',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myprofil',
            name='service',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myprofil',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myprofil',
            name='ville',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myprofil',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='demandegroupe',
            name='reponse',
            field=models.BooleanField(),
        ),
    ]
