# Generated by Django 2.0.3 on 2018-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langue',
            name='profils',
            field=models.ManyToManyField(blank=True, null=True, related_name='profils', to='main_app.Profil'),
        ),
    ]
