# Generated by Django 2.0.3 on 2018-05-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('SocialMedia', '0002_auto_20180510_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangueProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NiveauLangue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('natale', 'Langue natale'), ('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('expert', 'Expert')], max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='langue',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='langue',
            name='profils',
        ),
        migrations.AddField(
            model_name='langueprofil',
            name='langue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Langue'),
        ),
        migrations.AddField(
            model_name='langueprofil',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.NiveauLangue'),
        ),
        migrations.AddField(
            model_name='langueprofil',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
    ]
