# Generated by Django 2.0.3 on 2018-04-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0002_auto_20180426_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofil',
            name='token_email',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myprofil',
            name='token_email_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
