# Generated by Django 2.0.5 on 2018-05-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0003_offreemploi_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreemploi',
            name='groupe',
        ),
    ]
