# Generated by Django 2.0.3 on 2018-04-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0003_auto_20180428_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
