# Generated by Django 2.0.3 on 2018-05-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0004_auto_20180510_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveaulangue',
            name='niveau',
            field=models.CharField(max_length=300),
        ),
    ]
