# Generated by Django 2.0.3 on 2018-04-30 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('SocialMedia', '0004_auto_20180428_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='typeEntreprise',
        ),
        migrations.RemoveField(
            model_name='myprofil',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='myprofil',
            name='photo_couverture',
        ),
        migrations.RemoveField(
            model_name='myprofil',
            name='photo_profil',
        ),
        migrations.RemoveField(
            model_name='myprofil',
            name='user',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Image'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='liked_by',
            field=models.ManyToManyField(to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='demandeami',
            name='emetteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='demandeami',
            name='recepteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='demandegroupe',
            name='emetteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='adherents',
            field=models.ManyToManyField(related_name='adherent', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='admins',
            field=models.ManyToManyField(related_name='admin', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='createur', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='mederators',
            field=models.ManyToManyField(related_name='moderateur', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='photo_couverture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_cover', to='main_app.Image'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='photo_profil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_photo', to='main_app.Image'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='profil_to_notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='responseconversation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Image'),
        ),
        migrations.AlterField(
            model_name='statut',
            name='liked_by',
            field=models.ManyToManyField(related_name='like', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='statut',
            name='mur_profil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut_mur_profil', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='statut',
            name='publisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pub', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='suivie',
            name='followed_profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suive', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='suivie',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suiveur', to='main_app.Profil'),
        ),
        migrations.DeleteModel(
            name='Entreprise',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
        migrations.DeleteModel(
            name='TypeEntreprise',
        ),
    ]
