# Generated by Django 2.0.3 on 2018-05-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0004_remove_offreemploi_groupe'),
        ('SocialMedia', '0005_auto_20180510_1708'),
    ]

    operations = [
    ]
