# Generated by Django 2.0.5 on 2018-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0006_auto_20180512_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statut',
            name='likes',
            field=models.ManyToManyField(to='SocialMedia.Like'),
        ),
    ]
