# Generated by Django 2.0.3 on 2018-05-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0006_merge_20180512_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='lieu',
            field=models.CharField(default='Casablanca,maroc', max_length=300),
            preserve_default=False,
        ),
    ]
