# Generated by Django 2.0.5 on 2018-05-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0007_auto_20180512_1730'),
        ('SocialMedia', '0005_auto_20180510_1708'),
    ]

    operations = [
    ]
