# Generated by Django 2.0.3 on 2018-05-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0007_experience_lieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='resultat_obtenu',
        ),
    ]
