# Generated by Django 2.0.3 on 2018-05-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0008_auto_20180506_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecole',
            old_name='image',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='organisme',
            name='image',
        ),
        migrations.AddField(
            model_name='organisme',
            name='logo',
            field=models.ImageField(default=1, upload_to='SocialMedia/Image/'),
            preserve_default=False,
        ),
    ]
