# Generated by Django 2.0.5 on 2018-05-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0008_merge_20180513_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statut',
            name='mur_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Groupe'),
        ),
        migrations.AlterField(
            model_name='statut',
            name='mur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut_mur_profil', to='main_app.Profil'),
        ),
        migrations.AlterField(
            model_name='statut',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub', to='main_app.Profil'),
        ),
    ]
