# Generated by Django 2.0.3 on 2018-05-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0009_auto_20180506_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
