# Generated by Django 2.0.5 on 2018-05-14 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0009_auto_20180513_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Image'),
        ),
    ]
