# Generated by Django 2.0.3 on 2018-05-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0010_groupe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='statut_groupe',
            field=models.CharField(choices=[('publique', 'publique'), ('prive', 'privé')], max_length=255),
        ),
    ]
