# Generated by Django 2.0.5 on 2018-05-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0011_auto_20180514_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='SocialMedia.Like'),
        ),
    ]
