# Generated by Django 2.0.3 on 2018-05-06 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0011_auto_20180506_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='date_publication',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='nom_poste',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='poste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poste_recherche', to='SocialMedia.Poste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='type_emploi',
            field=models.CharField(choices=[('plein', 'Plein temps'), ('partiel', 'Temps partiel')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
