# Generated by Django 2.0.3 on 2018-05-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0012_auto_20180506_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreemploi',
            name='date_publication',
        ),
    ]
