# Generated by Django 2.0.5 on 2018-05-14 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0012_auto_20180514_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.Statut'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to='main_app.Profil'),
        ),
    ]
