# Generated by Django 2.0.3 on 2018-05-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0013_remove_offreemploi_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='date_publication',
            field=models.DateField(default='01/01/1991'),
            preserve_default=False,
        ),
    ]
