# Generated by Django 2.0.5 on 2018-05-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0013_auto_20180514_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statut',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='SocialMedia.Like'),
        ),
    ]
