# Generated by Django 2.0.3 on 2018-05-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0014_offreemploi_date_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreemploi',
            name='date_publication',
        ),
    ]
