# Generated by Django 2.0.5 on 2018-05-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0017_auto_20180515_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statut',
            name='contenu_statut',
            field=models.CharField(max_length=6000),
        ),
    ]
