# Generated by Django 2.0.3 on 2018-05-06 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0017_remove_offreemploi_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='date_publication',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
