# Generated by Django 2.0.3 on 2018-05-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0018_offreemploi_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='profil_postulants',
            field=models.ManyToManyField(blank=True, related_name='profil_postulants', to='main_app.Profil'),
        ),
    ]
