# Generated by Django 2.0.3 on 2018-05-08 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20180508_0108'),
        ('SocialMedia', '0019_auto_20180507_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='main_app.Profil')),
            ],
        ),
        migrations.RemoveField(
            model_name='reseausocialfile',
            name='user',
        ),
        migrations.AddField(
            model_name='reseausocialfile',
            name='comment',
            field=models.ManyToManyField(to='SocialMedia.Commentaire'),
        ),
        migrations.AddField(
            model_name='reseausocialfile',
            name='profil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Profil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statut',
            name='liked_by',
            field=models.ManyToManyField(related_name='statut_liked_by', to='main_app.Profil'),
        ),
        migrations.AddField(
            model_name='reseausocialfile',
            name='likes',
            field=models.ManyToManyField(to='SocialMedia.Like'),
        ),
    ]
