# Generated by Django 2.0.3 on 2018-05-13 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0008_remove_formation_resultat_obtenu'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='experience_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_profil', to='SocialMedia.Experience'),
        ),
        migrations.AddField(
            model_name='profil',
            name='formation_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formation_profil', to='SocialMedia.Formation'),
        ),
    ]
