# Generated by Django 2.0.3 on 2018-05-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='adresse_profile',
            field=models.CharField(default='h', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entreprise',
            name='civilité',
            field=models.CharField(default='mal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='adresse_profile',
            field=models.CharField(default='hh', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='civilité',
            field=models.CharField(default='mal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='is_first_marketplace',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='is_first_reseausocial',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
