# Generated by Django 2.0.3 on 2018-05-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180515_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='typeEntreprise',
            field=models.CharField(choices=[('petite', 'Petite entreprise'), ('grande', 'Grande entreprise'), ('tres petite', 'Très petite entreprise'), ('entreprise intermediaire', 'Entreprise de taille intermediaire')], max_length=255),
        ),
        migrations.AlterField(
            model_name='typeentreprise',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
