# Generated by Django 2.0.3 on 2018-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profil_is_first_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='image_entreprise',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profil',
            name='genre',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=1, verbose_name='Genre'),
        ),
    ]
