# Generated by Django 2.0.3 on 2018-05-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20180506_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofil',
            name='photo_couverture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_cover', to='main_app.Image'),
        ),
        migrations.AlterField(
            model_name='myprofil',
            name='photo_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_photo', to='main_app.Image'),
        ),
    ]
