# Generated by Django 2.0.3 on 2018-05-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180506_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='image_entreprise',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
