# Generated by Django 2.0.3 on 2018-05-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20180506_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='siteInternet',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='telephone',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='tel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
