# Generated by Django 2.0.3 on 2018-05-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20180506_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='genre',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=20, verbose_name='Genre'),
        ),
    ]
